# Generated by Django 5.1.6 on 2025-03-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organizationMaster',
            fields=[
                ('Ornganization_id', models.AutoField(primary_key=True, serialize=False)),
                ('Organization_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Phone_no', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=50)),
                ('Status', models.CharField(max_length=10)),
                ('Created_date', models.DateField()),
            ],
        ),
    ]
