# Generated by Django 5.1.6 on 2025-03-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userMaster',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Mobile_no', models.CharField(max_length=15)),
                ('Designation', models.CharField(max_length=25)),
                ('Gender', models.CharField(max_length=15)),
                ('Age', models.CharField(max_length=10)),
                ('Role', models.CharField(max_length=25)),
                ('Status', models.CharField(max_length=25)),
                ('Ornganization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodDonationApp.organizationmaster')),
            ],
        ),
    ]
