# Generated by Django 5.1.6 on 2025-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonationApp', '0002_usermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=25)),
            ],
        ),
    ]
