# Generated by Django 5.1.6 on 2025-03-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonationApp', '0003_loginmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMaster',
            fields=[
                ('Area_code', models.AutoField(primary_key=True, serialize=False)),
                ('Area_name', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=20)),
                ('Ornganization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodDonationApp.organizationmaster')),
            ],
        ),
    ]
