# Generated by Django 5.1.6 on 2025-03-13 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonationApp', '0004_areamaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalMaster',
            fields=[
                ('Hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('Hospital_name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=20)),
                ('Ornganization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodDonationApp.organizationmaster')),
            ],
        ),
    ]
