# Generated by Django 5.1.6 on 2025-03-13 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonationApp', '0005_hospitalmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='donorMaster',
            fields=[
                ('Donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Donor_name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('Age', models.CharField(max_length=5)),
                ('Address', models.CharField(max_length=500)),
                ('Phone_no', models.CharField(max_length=15)),
                ('Blood_group', models.CharField(max_length=10)),
                ('Donated_earlier', models.BooleanField(default=False)),
                ('Last_donation_date', models.DateField(blank=True, null=True)),
                ('Created_date', models.DateField()),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodDonationApp.areamaster')),
                ('Captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodDonationApp.usermaster')),
                ('Ornganization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodDonationApp.organizationmaster')),
            ],
        ),
    ]
