# Generated by Django 5.1.6 on 2025-03-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonationApp', '0006_donormaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='donormaster',
            name='Status',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
