# Generated by Django 5.1.6 on 2025-03-14 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonationApp', '0007_donormaster_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='donationDetails',
            fields=[
                ('Donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('Patient_bystander', models.CharField(max_length=50)),
                ('Contact_no', models.CharField(max_length=15)),
                ('Purpose', models.CharField(max_length=50)),
                ('Donation_date', models.DateField()),
                ('Donation_status', models.CharField(max_length=25)),
                ('Created_date', models.DateField()),
                ('Status', models.CharField(max_length=10)),
                ('Captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodDonationApp.usermaster')),
                ('Donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodDonationApp.donormaster')),
                ('Hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodDonationApp.hospitalmaster')),
                ('Ornganization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodDonationApp.organizationmaster')),
            ],
        ),
    ]
